server:
  servlet:
    session:
      timeout: 30M
  port: 8766
spring:
  datasource:
      url: jdbc:mysql://116.62.202.107:3306/painter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
      cache: false
      mode: HTML
      encoding: UTF-8
      servlet:
        content-type: text/html
